name: CI Native image build workflow
  
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4.1.0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build
      run: mvn --batch-mode --update-snapshots verify

    - name: Docker login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}

    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v3.0.0

    - name: Docker Setup Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: Dockerfile
        platforms: linux/amd64, linux/arm64/v8
        push: true
        tags: |
          alexholanda/algamoney-api:latest
          alexholanda/algamoney-api:v${{ github.run_number }}
